// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZwP7yIAM44qFYq0l65VHUSeshDukzwQk',
    appId: '1:180112132193:web:4fa81d0400f9b2397e8220',
    messagingSenderId: '180112132193',
    projectId: 'ecstatic-gantry-477200-f2',
    authDomain: 'ecstatic-gantry-477200-f2.firebaseapp.com',
    storageBucket: 'ecstatic-gantry-477200-f2.firebasestorage.app',
    measurementId: 'G-PQZL76EHYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAiNxXmrd6jpQee84Wv5_-IlL67nAdmTk',
    appId: '1:180112132193:android:e99d3b807c95dfb07e8220',
    messagingSenderId: '180112132193',
    projectId: 'ecstatic-gantry-477200-f2',
    storageBucket: 'ecstatic-gantry-477200-f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChyR16QeHlvbKGtRn373Edo4PBnGskkrY',
    appId: '1:180112132193:ios:76530ba54d0f53a47e8220',
    messagingSenderId: '180112132193',
    projectId: 'ecstatic-gantry-477200-f2',
    storageBucket: 'ecstatic-gantry-477200-f2.firebasestorage.app',
    iosBundleId: 'com.example.venv',
  );

}