// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ2Hxqcpkv9DiuBBbSrlj-uKXTb1OF9Wc',
    appId: '1:528750738531:web:1d2351b3b46c458e5b8c56',
    messagingSenderId: '528750738531',
    projectId: 'venv-da7c9',
    authDomain: 'venv-da7c9.firebaseapp.com',
    storageBucket: 'venv-da7c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCulzbsfmRX7zhbNMUgrgDm-94-HdzSSj4',
    appId: '1:528750738531:android:c04feb45ca3a6d3e5b8c56',
    messagingSenderId: '528750738531',
    projectId: 'venv-da7c9',
    storageBucket: 'venv-da7c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoo-Jp-Z9tixM-ShulYk6OBLlrqPR8xc4',
    appId: '1:528750738531:ios:720f90cfc7cbe84a5b8c56',
    messagingSenderId: '528750738531',
    projectId: 'venv-da7c9',
    storageBucket: 'venv-da7c9.firebasestorage.app',
    iosBundleId: 'com.example.venv',
  );
}
